# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\xa1\x01\n\x08Purchase\x12\x13\n\x0bpurchase_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\x05\x12\x10\n\x08\x61rticles\x18\x03 \x03(\x05\x12\x13\n\x0btotal_price\x18\x04 \x01(\x01\x12$\n\x04type\x18\x05 \x01(\x0e\x32\x16.example.Purchase.Type\"\x1e\n\x04Type\x12\n\n\x06ONLINE\x10\x00\x12\n\n\x06RETAIL\x10\x01\"\x8e\x01\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66orename\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0b\n\x03ssn\x18\x04 \x01(\x05\x12\x10\n\x08zip_code\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12$\n\tpurchases\x18\x07 \x03(\x0b\x32\x11.example.Purchase\"g\n\x17\x43ustomerServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12$\n\tcustomers\x18\x03 \x03(\x0b\x32\x11.example.Customer\"\x1e\n\x0cRichCustomer\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x32\xe5\x01\n\x0f\x43ustomerService\x12\x42\n\x0b\x41\x64\x64\x43ustomer\x12\x11.example.Customer\x1a .example.CustomerServiceResponse\x12\x46\n\rSendPurchases\x12\x11.example.Purchase\x1a .example.CustomerServiceResponse(\x01\x12\x46\n\rRichCustomers\x12 .example.CustomerServiceResponse\x1a\x11.example.Customer0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PURCHASE._serialized_start=27
  _PURCHASE._serialized_end=188
  _PURCHASE_TYPE._serialized_start=158
  _PURCHASE_TYPE._serialized_end=188
  _CUSTOMER._serialized_start=191
  _CUSTOMER._serialized_end=333
  _CUSTOMERSERVICERESPONSE._serialized_start=335
  _CUSTOMERSERVICERESPONSE._serialized_end=438
  _RICHCUSTOMER._serialized_start=440
  _RICHCUSTOMER._serialized_end=470
  _CUSTOMERSERVICE._serialized_start=473
  _CUSTOMERSERVICE._serialized_end=702
# @@protoc_insertion_point(module_scope)
